sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull karthequian/gruyere:latest
- docker pull gauntlt/gauntlt
- docker run --rm -d -p 8008:8008 karthequian/gruyere:latest
- docker ps
- docker ps -a

script:
  - pwd
  - cat /etc/passwd
  - ifconfig -a
  - docker run -t --rm -v $(pwd):/working -w /working gauntlt/gauntlt ./attacks/hello_world/hello-world.attack

