# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/karthequian/security-testing-class
    steps:
      - checkout
      - run: |
        docker pull karthequian/gruyere:latest
        docker pull gauntlt/gauntlt
      - run: |
        docker run --rm -d -p 8008:8008 --name gruyere karthequian/gruyere:latest
        docker ps -a
      - run: ./scripts/travis-config.sh
      - run: cat ./config/cucumber.yml
      - run: |
          # creating dummy container which will hold a volume with config
          docker create -v /working --name configs gauntlt/gauntlt ./attacks/hello_world/hello-world.attack
          # copying config file into this volume
          docker cp path/in/your/source/code/app_config.yml configs:/cfg
          # starting application container using this volume
          docker run --volumes-from configs  -w /working gauntlt/gauntlt
      - run: docker run -t --rm -v $(pwd):/working --network container:gruyere -w /working gauntlt/gauntlt ./attacks/hello_world/hello-world.attack
